name: button_animations
description: A package that helps you make highly customizable animated 3d-buttons.

publish_to: none

version: 2.0.0+230104

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
